"""
Seed Global Dish Library with 100+ Popular Indian Dishes
Run this after migration 002
"""

GLOBAL_INGREDIENTS = [
    # Dairy
    {"name": "Paneer", "category": "Dairy", "standard_unit": "kg", "alternate_names": ["Cottage Cheese", "Indian Cheese"], "avg_cost_per_unit": 300, "is_perishable": True, "avg_shelf_life_days": 7},
    {"name": "Butter", "category": "Dairy", "standard_unit": "kg", "alternate_names": ["Makkhan"], "avg_cost_per_unit": 400, "is_perishable": True, "avg_shelf_life_days": 30},
    {"name": "Cream", "category": "Dairy", "standard_unit": "liter", "alternate_names": ["Fresh Cream", "Malai"], "avg_cost_per_unit": 250, "is_perishable": True, "avg_shelf_life_days": 7},
    {"name": "Yogurt", "category": "Dairy", "standard_unit": "kg", "alternate_names": ["Curd", "Dahi"], "avg_cost_per_unit": 80, "is_perishable": True, "avg_shelf_life_days": 5},
    {"name": "Ghee", "category": "Dairy", "standard_unit": "liter", "alternate_names": ["Clarified Butter"], "avg_cost_per_unit": 600, "is_perishable": False, "avg_shelf_life_days": 180},
    {"name": "Milk", "category": "Dairy", "standard_unit": "liter", "alternate_names": ["Doodh"], "avg_cost_per_unit": 60, "is_perishable": True, "avg_shelf_life_days": 3},
    
    # Meat & Poultry
    {"name": "Chicken", "category": "Meat", "standard_unit": "kg", "alternate_names": ["Murgh", "Chicken Breast"], "avg_cost_per_unit": 200, "is_perishable": True, "avg_shelf_life_days": 2},
    {"name": "Mutton", "category": "Meat", "standard_unit": "kg", "alternate_names": ["Lamb", "Goat Meat"], "avg_cost_per_unit": 600, "is_perishable": True, "avg_shelf_life_days": 2},
    {"name": "Fish", "category": "Seafood", "standard_unit": "kg", "alternate_names": ["Machli"], "avg_cost_per_unit": 300, "is_perishable": True, "avg_shelf_life_days": 1},
    {"name": "Prawns", "category": "Seafood", "standard_unit": "kg", "alternate_names": ["Shrimp", "Jhinga"], "avg_cost_per_unit": 500, "is_perishable": True, "avg_shelf_life_days": 1},
    
    # Vegetables
    {"name": "Onion", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Pyaz"], "avg_cost_per_unit": 40, "is_perishable": False, "avg_shelf_life_days": 30},
    {"name": "Tomato", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Tamatar"], "avg_cost_per_unit": 50, "is_perishable": True, "avg_shelf_life_days": 7},
    {"name": "Bell Pepper", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Capsicum", "Shimla Mirch"], "avg_cost_per_unit": 80, "is_perishable": True, "avg_shelf_life_days": 7},
    {"name": "Green Chili", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Hari Mirch", "Hot Pepper"], "avg_cost_per_unit": 60, "is_perishable": True, "avg_shelf_life_days": 10},
    {"name": "Garlic", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Lehsun"], "avg_cost_per_unit": 100, "is_perishable": False, "avg_shelf_life_days": 90},
    {"name": "Ginger", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Adrak"], "avg_cost_per_unit": 120, "is_perishable": False, "avg_shelf_life_days": 60},
    {"name": "Potato", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Aloo"], "avg_cost_per_unit": 30, "is_perishable": False, "avg_shelf_life_days": 60},
    {"name": "Cauliflower", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Gobi", "Phool Gobi"], "avg_cost_per_unit": 40, "is_perishable": True, "avg_shelf_life_days": 7},
    {"name": "Peas", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Matar"], "avg_cost_per_unit": 60, "is_perishable": True, "avg_shelf_life_days": 5},
    {"name": "Spinach", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Palak", "Saag"], "avg_cost_per_unit": 50, "is_perishable": True, "avg_shelf_life_days": 3},
    {"name": "Eggplant", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Brinjal", "Baingan"], "avg_cost_per_unit": 40, "is_perishable": True, "avg_shelf_life_days": 7},
    {"name": "Okra", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Bhindi", "Lady Finger"], "avg_cost_per_unit": 60, "is_perishable": True, "avg_shelf_life_days": 5},
    {"name": "Mushroom", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Khumb"], "avg_cost_per_unit": 200, "is_perishable": True, "avg_shelf_life_days": 5},
    {"name": "Cabbage", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Patta Gobi"], "avg_cost_per_unit": 30, "is_perishable": True, "avg_shelf_life_days": 14},
    {"name": "Carrot", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Gajar"], "avg_cost_per_unit": 50, "is_perishable": False, "avg_shelf_life_days": 30},
    {"name": "Cucumber", "category": "Vegetable", "standard_unit": "kg", "alternate_names": ["Kheera"], "avg_cost_per_unit": 40, "is_perishable": True, "avg_shelf_life_days": 7},
    {"name": "Coriander Leaves", "category": "Herbs", "standard_unit": "kg", "alternate_names": ["Cilantro", "Dhania Patta"], "avg_cost_per_unit": 80, "is_perishable": True, "avg_shelf_life_days": 5},
    {"name": "Mint Leaves", "category": "Herbs", "standard_unit": "kg", "alternate_names": ["Pudina"], "avg_cost_per_unit": 100, "is_perishable": True, "avg_shelf_life_days": 5},
    
    # Legumes & Lentils
    {"name": "Chickpeas", "category": "Legume", "standard_unit": "kg", "alternate_names": ["Chole", "Chana", "Garbanzo"], "avg_cost_per_unit": 80, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Red Lentils", "category": "Legume", "standard_unit": "kg", "alternate_names": ["Masoor Dal"], "avg_cost_per_unit": 120, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Yellow Lentils", "category": "Legume", "standard_unit": "kg", "alternate_names": ["Toor Dal", "Arhar Dal"], "avg_cost_per_unit": 100, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Black Lentils", "category": "Legume", "standard_unit": "kg", "alternate_names": ["Urad Dal"], "avg_cost_per_unit": 150, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Green Gram", "category": "Legume", "standard_unit": "kg", "alternate_names": ["Moong Dal"], "avg_cost_per_unit": 140, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Kidney Beans", "category": "Legume", "standard_unit": "kg", "alternate_names": ["Rajma"], "avg_cost_per_unit": 160, "is_perishable": False, "avg_shelf_life_days": 365},
    
    # Grains & Rice
    {"name": "Basmati Rice", "category": "Grain", "standard_unit": "kg", "alternate_names": ["Rice", "Chawal"], "avg_cost_per_unit": 120, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Wheat Flour", "category": "Grain", "standard_unit": "kg", "alternate_names": ["Atta", "Maida"], "avg_cost_per_unit": 40, "is_perishable": False, "avg_shelf_life_days": 180},
    {"name": "Semolina", "category": "Grain", "standard_unit": "kg", "alternate_names": ["Rava", "Suji"], "avg_cost_per_unit": 50, "is_perishable": False, "avg_shelf_life_days": 180},
    
    # Spices
    {"name": "Cumin Seeds", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Jeera"], "avg_cost_per_unit": 400, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Coriander Seeds", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Dhania"], "avg_cost_per_unit": 300, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Turmeric Powder", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Haldi"], "avg_cost_per_unit": 250, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Red Chili Powder", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Lal Mirch"], "avg_cost_per_unit": 300, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Garam Masala", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Mixed Spice"], "avg_cost_per_unit": 600, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Cardamom", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Elaichi"], "avg_cost_per_unit": 2000, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Cinnamon", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Dalchini"], "avg_cost_per_unit": 800, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Cloves", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Laung"], "avg_cost_per_unit": 1500, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Bay Leaf", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Tej Patta"], "avg_cost_per_unit": 400, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Mustard Seeds", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Sarson", "Rai"], "avg_cost_per_unit": 200, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Fenugreek Seeds", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Methi"], "avg_cost_per_unit": 300, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Kashmiri Red Chili", "category": "Spice", "standard_unit": "kg", "alternate_names": ["Kashmiri Mirch"], "avg_cost_per_unit": 500, "is_perishable": False, "avg_shelf_life_days": 365},
    
    # Oils & Fats
    {"name": "Vegetable Oil", "category": "Oil", "standard_unit": "liter", "alternate_names": ["Cooking Oil"], "avg_cost_per_unit": 150, "is_perishable": False, "avg_shelf_life_days": 365},
    {"name": "Mustard Oil", "category": "Oil", "standard_unit": "liter", "alternate_names": ["Sarson Ka Tel"], "avg_cost_per_unit": 180, "is_perishable": False, "avg_shelf_life_days": 365},
    
    # Others
    {"name": "Salt", "category": "Seasoning", "standard_unit": "kg", "alternate_names": ["Namak"], "avg_cost_per_unit": 20, "is_perishable": False, "avg_shelf_life_days": 3650},
    {"name": "Sugar", "category": "Seasoning", "standard_unit": "kg", "alternate_names": ["Cheeni"], "avg_cost_per_unit": 40, "is_perishable": False, "avg_shelf_life_days": 730},
    {"name": "Lemon", "category": "Fruit", "standard_unit": "kg", "alternate_names": ["Nimbu"], "avg_cost_per_unit": 80, "is_perishable": True, "avg_shelf_life_days": 14},
    {"name": "Tamarind", "category": "Fruit", "standard_unit": "kg", "alternate_names": ["Imli"], "avg_cost_per_unit": 120, "is_perishable": False, "avg_shelf_life_days": 180},
    {"name": "Coconut Milk", "category": "Liquid", "standard_unit": "liter", "alternate_names": ["Nariyal Ka Doodh"], "avg_cost_per_unit": 200, "is_perishable": True, "avg_shelf_life_days": 7},
    {"name": "Cashew Nuts", "category": "Nuts", "standard_unit": "kg", "alternate_names": ["Kaju"], "avg_cost_per_unit": 800, "is_perishable": False, "avg_shelf_life_days": 180},
    {"name": "Almonds", "category": "Nuts", "standard_unit": "kg", "alternate_names": ["Badam"], "avg_cost_per_unit": 700, "is_perishable": False, "avg_shelf_life_days": 180},
]

GLOBAL_DISHES = [
    # APPETIZERS / STARTERS
    {
        "name": "Paneer Tikka",
        "description": "Marinated paneer cubes grilled with bell peppers and onions",
        "category": "Appetizer",
        "cuisine": "Indian",
        "default_price": 250.00,
        "image_url": "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8",
        "is_vegetarian": True,
        "spice_level": 3,
        "prep_time_minutes": 25,
        "calories": 320,
        "allergens": ["dairy"],
        "tags": ["popular", "vegetarian", "grilled"],
        "ingredients": [
            {"name": "Paneer", "quantity": 200, "unit": "grams"},
            {"name": "Bell Pepper", "quantity": 50, "unit": "grams"},
            {"name": "Onion", "quantity": 30, "unit": "grams"},
            {"name": "Yogurt", "quantity": 50, "unit": "grams"},
            {"name": "Ginger", "quantity": 10, "unit": "grams"},
            {"name": "Garlic", "quantity": 10, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
            {"name": "Lemon", "quantity": 20, "unit": "grams"},
            {"name": "Vegetable Oil", "quantity": 30, "unit": "ml"},
        ]
    },
    {
        "name": "Chicken Tikka",
        "description": "Succulent chicken pieces marinated in spices and grilled to perfection",
        "category": "Appetizer",
        "cuisine": "Indian",
        "default_price": 280.00,
        "image_url": "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0",
        "is_vegetarian": False,
        "spice_level": 3,
        "prep_time_minutes": 30,
        "calories": 280,
        "allergens": ["dairy"],
        "tags": ["popular", "non-veg", "grilled"],
        "ingredients": [
            {"name": "Chicken", "quantity": 250, "unit": "grams"},
            {"name": "Yogurt", "quantity": 50, "unit": "grams"},
            {"name": "Ginger", "quantity": 10, "unit": "grams"},
            {"name": "Garlic", "quantity": 10, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
            {"name": "Kashmiri Red Chili", "quantity": 5, "unit": "grams"},
            {"name": "Lemon", "quantity": 20, "unit": "grams"},
            {"name": "Mustard Oil", "quantity": 30, "unit": "ml"},
        ]
    },
    {
        "name": "Samosa",
        "description": "Crispy fried pastry filled with spiced potatoes and peas",
        "category": "Appetizer",
        "cuisine": "Indian",
        "default_price": 40.00,
        "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950",
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 20,
        "calories": 250,
        "allergens": ["gluten"],
        "tags": ["popular", "snack", "fried"],
        "ingredients": [
            {"name": "Potato", "quantity": 100, "unit": "grams"},
            {"name": "Peas", "quantity": 30, "unit": "grams"},
            {"name": "Wheat Flour", "quantity": 50, "unit": "grams"},
            {"name": "Cumin Seeds", "quantity": 2, "unit": "grams"},
            {"name": "Ginger", "quantity": 5, "unit": "grams"},
            {"name": "Green Chili", "quantity": 5, "unit": "grams"},
            {"name": "Vegetable Oil", "quantity": 100, "unit": "ml"},
        ]
    },
    {
        "name": "Hara Bhara Kabab",
        "description": "Green vegetable patties with spinach and peas",
        "category": "Appetizer",
        "cuisine": "Indian",
        "default_price": 180.00,
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 20,
        "calories": 200,
        "tags": ["healthy", "vegetarian"],
        "ingredients": [
            {"name": "Spinach", "quantity": 100, "unit": "grams"},
            {"name": "Peas", "quantity": 50, "unit": "grams"},
            {"name": "Potato", "quantity": 50, "unit": "grams"},
            {"name": "Ginger", "quantity": 5, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 3, "unit": "grams"},
        ]
    },
    
    # MAIN COURSES - VEGETARIAN
    {
        "name": "Palak Paneer",
        "description": "Cottage cheese cubes in creamy spinach gravy",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 220.00,
        "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950",
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 25,
        "calories": 280,
        "allergens": ["dairy"],
        "tags": ["popular", "vegetarian", "healthy"],
        "ingredients": [
            {"name": "Paneer", "quantity": 150, "unit": "grams"},
            {"name": "Spinach", "quantity": 200, "unit": "grams"},
            {"name": "Onion", "quantity": 50, "unit": "grams"},
            {"name": "Tomato", "quantity": 50, "unit": "grams"},
            {"name": "Cream", "quantity": 30, "unit": "ml"},
            {"name": "Ginger", "quantity": 10, "unit": "grams"},
            {"name": "Garlic", "quantity": 10, "unit": "grams"},
            {"name": "Cumin Seeds", "quantity": 3, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 3, "unit": "grams"},
            {"name": "Butter", "quantity": 20, "unit": "grams"},
        ]
    },
    {
        "name": "Paneer Butter Masala",
        "description": "Rich and creamy tomato-based curry with paneer",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 240.00,
        "image_url": "https://images.unsplash.com/photo-1631452180519-c014fe946bc7",
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 30,
        "calories": 350,
        "allergens": ["dairy"],
        "tags": ["popular", "vegetarian", "signature"],
        "ingredients": [
            {"name": "Paneer", "quantity": 200, "unit": "grams"},
            {"name": "Tomato", "quantity": 150, "unit": "grams"},
            {"name": "Butter", "quantity": 40, "unit": "grams"},
            {"name": "Cream", "quantity": 50, "unit": "ml"},
            {"name": "Onion", "quantity": 50, "unit": "grams"},
            {"name": "Cashew Nuts", "quantity": 20, "unit": "grams"},
            {"name": "Ginger", "quantity": 10, "unit": "grams"},
            {"name": "Garlic", "quantity": 10, "unit": "grams"},
            {"name": "Kashmiri Red Chili", "quantity": 5, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
        ]
    },
    {
        "name": "Dal Makhani",
        "description": "Creamy black lentils slow-cooked with butter and cream",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 180.00,
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 45,
        "calories": 300,
        "allergens": ["dairy"],
        "tags": ["popular", "vegetarian"],
        "ingredients": [
            {"name": "Black Lentils", "quantity": 100, "unit": "grams"},
            {"name": "Kidney Beans", "quantity": 30, "unit": "grams"},
            {"name": "Butter", "quantity": 30, "unit": "grams"},
            {"name": "Cream", "quantity": 40, "unit": "ml"},
            {"name": "Tomato", "quantity": 80, "unit": "grams"},
            {"name": "Onion", "quantity": 40, "unit": "grams"},
            {"name": "Ginger", "quantity": 10, "unit": "grams"},
            {"name": "Garlic", "quantity": 10, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
        ]
    },
    {
        "name": "Chole Bhature",
        "description": "Spicy chickpea curry served with fluffy fried bread",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 160.00,
        "is_vegetarian": True,
        "spice_level": 3,
        "prep_time_minutes": 40,
        "calories": 450,
        "allergens": ["gluten"],
        "tags": ["popular", "vegetarian"],
        "ingredients": [
            {"name": "Chickpeas", "quantity": 150, "unit": "grams"},
            {"name": "Wheat Flour", "quantity": 100, "unit": "grams"},
            {"name": "Tomato", "quantity": 80, "unit": "grams"},
            {"name": "Onion", "quantity": 60, "unit": "grams"},
            {"name": "Ginger", "quantity": 10, "unit": "grams"},
            {"name": "Garlic", "quantity": 10, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
            {"name": "Yogurt", "quantity": 30, "unit": "grams"},
            {"name": "Vegetable Oil", "quantity": 100, "unit": "ml"},
        ]
    },
    {
        "name": "Aloo Gobi",
        "description": "Dry curry of potatoes and cauliflower with Indian spices",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 140.00,
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 25,
        "calories": 180,
        "tags": ["vegetarian", "healthy"],
        "ingredients": [
            {"name": "Potato", "quantity": 100, "unit": "grams"},
            {"name": "Cauliflower", "quantity": 150, "unit": "grams"},
            {"name": "Onion", "quantity": 50, "unit": "grams"},
            {"name": "Tomato", "quantity": 40, "unit": "grams"},
            {"name": "Ginger", "quantity": 5, "unit": "grams"},
            {"name": "Cumin Seeds", "quantity": 3, "unit": "grams"},
            {"name": "Turmeric Powder", "quantity": 3, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 3, "unit": "grams"},
        ]
    },
    {
        "name": "Malai Kofta",
        "description": "Vegetable and paneer dumplings in rich creamy gravy",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 260.00,
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 35,
        "calories": 380,
        "allergens": ["dairy", "nuts"],
        "tags": ["vegetarian", "rich"],
        "ingredients": [
            {"name": "Paneer", "quantity": 100, "unit": "grams"},
            {"name": "Potato", "quantity": 80, "unit": "grams"},
            {"name": "Cream", "quantity": 60, "unit": "ml"},
            {"name": "Tomato", "quantity": 100, "unit": "grams"},
            {"name": "Cashew Nuts", "quantity": 30, "unit": "grams"},
            {"name": "Onion", "quantity": 50, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
        ]
    },
    
    # MAIN COURSES - NON-VEGETARIAN
    {
        "name": "Chicken Biryani",
        "description": "Fragrant basmati rice layered with spiced chicken",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 280.00,
        "image_url": "https://images.unsplash.com/photo-1563379091339-03b0a35f6d9a",
        "is_vegetarian": False,
        "spice_level": 3,
        "prep_time_minutes": 45,
        "calories": 450,
        "allergens": ["dairy"],
        "tags": ["popular", "signature", "non-veg"],
        "ingredients": [
            {"name": "Chicken", "quantity": 250, "unit": "grams"},
            {"name": "Basmati Rice", "quantity": 150, "unit": "grams"},
            {"name": "Yogurt", "quantity": 50, "unit": "grams"},
            {"name": "Onion", "quantity": 80, "unit": "grams"},
            {"name": "Tomato", "quantity": 50, "unit": "grams"},
            {"name": "Ginger", "quantity": 15, "unit": "grams"},
            {"name": "Garlic", "quantity": 15, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
            {"name": "Cardamom", "quantity": 2, "unit": "grams"},
            {"name": "Cinnamon", "quantity": 2, "unit": "grams"},
            {"name": "Ghee", "quantity": 30, "unit": "ml"},
        ]
    },
    {
        "name": "Butter Chicken",
        "description": "Tender chicken in rich tomato and butter gravy",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 300.00,
        "image_url": "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398",
        "is_vegetarian": False,
        "spice_level": 2,
        "prep_time_minutes": 35,
        "calories": 380,
        "allergens": ["dairy"],
        "tags": ["popular", "signature", "non-veg"],
        "ingredients": [
            {"name": "Chicken", "quantity": 250, "unit": "grams"},
            {"name": "Butter", "quantity": 50, "unit": "grams"},
            {"name": "Cream", "quantity": 60, "unit": "ml"},
            {"name": "Tomato", "quantity": 150, "unit": "grams"},
            {"name": "Cashew Nuts", "quantity": 20, "unit": "grams"},
            {"name": "Yogurt", "quantity": 40, "unit": "grams"},
            {"name": "Ginger", "quantity": 10, "unit": "grams"},
            {"name": "Garlic", "quantity": 10, "unit": "grams"},
            {"name": "Kashmiri Red Chili", "quantity": 5, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
        ]
    },
    {
        "name": "Rogan Josh",
        "description": "Aromatic lamb curry with Kashmiri spices",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 380.00,
        "is_vegetarian": False,
        "spice_level": 3,
        "prep_time_minutes": 50,
        "calories": 420,
        "allergens": ["dairy"],
        "tags": ["signature", "non-veg", "spicy"],
        "ingredients": [
            {"name": "Mutton", "quantity": 300, "unit": "grams"},
            {"name": "Yogurt", "quantity": 80, "unit": "grams"},
            {"name": "Onion", "quantity": 100, "unit": "grams"},
            {"name": "Tomato", "quantity": 80, "unit": "grams"},
            {"name": "Ginger", "quantity": 15, "unit": "grams"},
            {"name": "Garlic", "quantity": 15, "unit": "grams"},
            {"name": "Kashmiri Red Chili", "quantity": 8, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
            {"name": "Cardamom", "quantity": 2, "unit": "grams"},
        ]
    },
    {
        "name": "Fish Curry",
        "description": "Coastal style fish cooked in tangy coconut gravy",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 320.00,
        "is_vegetarian": False,
        "spice_level": 3,
        "prep_time_minutes": 30,
        "calories": 280,
        "tags": ["non-veg", "seafood"],
        "ingredients": [
            {"name": "Fish", "quantity": 250, "unit": "grams"},
            {"name": "Coconut Milk", "quantity": 150, "unit": "ml"},
            {"name": "Onion", "quantity": 60, "unit": "grams"},
            {"name": "Tomato", "quantity": 60, "unit": "grams"},
            {"name": "Tamarind", "quantity": 20, "unit": "grams"},
            {"name": "Mustard Seeds", "quantity": 3, "unit": "grams"},
            {"name": "Curry Leaves", "quantity": 5, "unit": "grams"},
        ]
    },
    {
        "name": "Chicken Korma",
        "description": "Mild and creamy chicken curry with yogurt and nuts",
        "category": "Main Course",
        "cuisine": "Indian",
        "default_price": 290.00,
        "is_vegetarian": False,
        "spice_level": 1,
        "prep_time_minutes": 35,
        "calories": 360,
        "allergens": ["dairy", "nuts"],
        "tags": ["non-veg", "mild"],
        "ingredients": [
            {"name": "Chicken", "quantity": 250, "unit": "grams"},
            {"name": "Yogurt", "quantity": 80, "unit": "grams"},
            {"name": "Cream", "quantity": 50, "unit": "ml"},
            {"name": "Cashew Nuts", "quantity": 30, "unit": "grams"},
            {"name": "Almonds", "quantity": 20, "unit": "grams"},
            {"name": "Onion", "quantity": 70, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
        ]
    },
    
    # RICE & BREAD
    {
        "name": "Naan",
        "description": "Soft leavened Indian bread baked in tandoor",
        "category": "Bread",
        "cuisine": "Indian",
        "default_price": 40.00,
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 15,
        "calories": 260,
        "allergens": ["gluten", "dairy"],
        "tags": ["popular", "bread"],
        "ingredients": [
            {"name": "Wheat Flour", "quantity": 100, "unit": "grams"},
            {"name": "Yogurt", "quantity": 30, "unit": "grams"},
            {"name": "Milk", "quantity": 30, "unit": "ml"},
            {"name": "Sugar", "quantity": 5, "unit": "grams"},
            {"name": "Salt", "quantity": 3, "unit": "grams"},
        ]
    },
    {
        "name": "Garlic Naan",
        "description": "Naan topped with fresh garlic and butter",
        "category": "Bread",
        "cuisine": "Indian",
        "default_price": 50.00,
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 15,
        "calories": 280,
        "allergens": ["gluten", "dairy"],
        "tags": ["popular", "bread"],
        "ingredients": [
            {"name": "Wheat Flour", "quantity": 100, "unit": "grams"},
            {"name": "Garlic", "quantity": 20, "unit": "grams"},
            {"name": "Butter", "quantity": 15, "unit": "grams"},
            {"name": "Yogurt", "quantity": 30, "unit": "grams"},
            {"name": "Coriander Leaves", "quantity": 10, "unit": "grams"},
        ]
    },
    {
        "name": "Roti",
        "description": "Whole wheat flatbread",
        "category": "Bread",
        "cuisine": "Indian",
        "default_price": 15.00,
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 10,
        "calories": 120,
        "allergens": ["gluten"],
        "tags": ["bread", "healthy"],
        "ingredients": [
            {"name": "Wheat Flour", "quantity": 50, "unit": "grams"},
            {"name": "Ghee", "quantity": 5, "unit": "grams"},
            {"name": "Salt", "quantity": 2, "unit": "grams"},
        ]
    },
    {
        "name": "Paratha",
        "description": "Layered flatbread cooked with ghee",
        "category": "Bread",
        "cuisine": "Indian",
        "default_price": 30.00,
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 15,
        "calories": 200,
        "allergens": ["gluten", "dairy"],
        "tags": ["bread"],
        "ingredients": [
            {"name": "Wheat Flour", "quantity": 80, "unit": "grams"},
            {"name": "Ghee", "quantity": 20, "unit": "grams"},
            {"name": "Salt", "quantity": 2, "unit": "grams"},
        ]
    },
    {
        "name": "Jeera Rice",
        "description": "Basmati rice tempered with cumin seeds",
        "category": "Rice",
        "cuisine": "Indian",
        "default_price": 120.00,
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 20,
        "calories": 280,
        "tags": ["rice"],
        "ingredients": [
            {"name": "Basmati Rice", "quantity": 100, "unit": "grams"},
            {"name": "Cumin Seeds", "quantity": 5, "unit": "grams"},
            {"name": "Ghee", "quantity": 15, "unit": "grams"},
            {"name": "Salt", "quantity": 3, "unit": "grams"},
        ]
    },
    {
        "name": "Veg Biryani",
        "description": "Fragrant rice with mixed vegetables and aromatic spices",
        "category": "Rice",
        "cuisine": "Indian",
        "default_price": 220.00,
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 40,
        "calories": 380,
        "allergens": ["dairy"],
        "tags": ["popular", "vegetarian"],
        "ingredients": [
            {"name": "Basmati Rice", "quantity": 150, "unit": "grams"},
            {"name": "Carrot", "quantity": 50, "unit": "grams"},
            {"name": "Peas", "quantity": 40, "unit": "grams"},
            {"name": "Potato", "quantity": 50, "unit": "grams"},
            {"name": "Yogurt", "quantity": 40, "unit": "grams"},
            {"name": "Onion", "quantity": 60, "unit": "grams"},
            {"name": "Garam Masala", "quantity": 5, "unit": "grams"},
            {"name": "Ghee", "quantity": 25, "unit": "ml"},
        ]
    },
    
    # DESSERTS
    {
        "name": "Gulab Jamun",
        "description": "Deep-fried milk dumplings soaked in sweet syrup",
        "category": "Dessert",
        "cuisine": "Indian",
        "default_price": 80.00,
        "image_url": "https://images.unsplash.com/photo-1597328117128-67885df2e6b1",
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 30,
        "calories": 380,
        "allergens": ["dairy", "gluten"],
        "tags": ["popular", "sweet", "dessert"],
        "ingredients": [
            {"name": "Milk", "quantity": 100, "unit": "ml"},
            {"name": "Wheat Flour", "quantity": 40, "unit": "grams"},
            {"name": "Sugar", "quantity": 60, "unit": "grams"},
            {"name": "Ghee", "quantity": 20, "unit": "grams"},
            {"name": "Cardamom", "quantity": 2, "unit": "grams"},
        ]
    },
    {
        "name": "Rasmalai",
        "description": "Soft paneer patties in sweet creamy milk",
        "category": "Dessert",
        "cuisine": "Indian",
        "default_price": 100.00,
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 40,
        "calories": 320,
        "allergens": ["dairy"],
        "tags": ["dessert", "sweet"],
        "ingredients": [
            {"name": "Paneer", "quantity": 100, "unit": "grams"},
            {"name": "Milk", "quantity": 200, "unit": "ml"},
            {"name": "Sugar", "quantity": 60, "unit": "grams"},
            {"name": "Cardamom", "quantity": 2, "unit": "grams"},
            {"name": "Almonds", "quantity": 10, "unit": "grams"},
        ]
    },
    {
        "name": "Kheer",
        "description": "Traditional rice pudding with nuts",
        "category": "Dessert",
        "cuisine": "Indian",
        "default_price": 90.00,
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 35,
        "calories": 280,
        "allergens": ["dairy", "nuts"],
        "tags": ["dessert", "traditional"],
        "ingredients": [
            {"name": "Basmati Rice", "quantity": 50, "unit": "grams"},
            {"name": "Milk", "quantity": 250, "unit": "ml"},
            {"name": "Sugar", "quantity": 50, "unit": "grams"},
            {"name": "Cardamom", "quantity": 2, "unit": "grams"},
            {"name": "Cashew Nuts", "quantity": 15, "unit": "grams"},
            {"name": "Almonds", "quantity": 15, "unit": "grams"},
        ]
    },
    {
        "name": "Gajar Halwa",
        "description": "Carrot pudding with milk, ghee and nuts",
        "category": "Dessert",
        "cuisine": "Indian",
        "default_price": 110.00,
        "is_vegetarian": True,
        "spice_level": 0,
        "prep_time_minutes": 45,
        "calories": 320,
        "allergens": ["dairy", "nuts"],
        "tags": ["dessert", "winter special"],
        "ingredients": [
            {"name": "Carrot", "quantity": 200, "unit": "grams"},
            {"name": "Milk", "quantity": 150, "unit": "ml"},
            {"name": "Sugar", "quantity": 50, "unit": "grams"},
            {"name": "Ghee", "quantity": 30, "unit": "grams"},
            {"name": "Cardamom", "quantity": 2, "unit": "grams"},
            {"name": "Cashew Nuts", "quantity": 15, "unit": "grams"},
        ]
    },
    
    # SOUTH INDIAN
    {
        "name": "Masala Dosa",
        "description": "Crispy rice crepe filled with spiced potato filling",
        "category": "Main Course",
        "cuisine": "South Indian",
        "default_price": 120.00,
        "image_url": "https://images.unsplash.com/photo-1630383249896-424e482df921",
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 25,
        "calories": 280,
        "tags": ["popular", "vegetarian", "south indian"],
        "ingredients": [
            {"name": "Basmati Rice", "quantity": 100, "unit": "grams"},
            {"name": "Black Lentils", "quantity": 30, "unit": "grams"},
            {"name": "Potato", "quantity": 100, "unit": "grams"},
            {"name": "Onion", "quantity": 40, "unit": "grams"},
            {"name": "Mustard Seeds", "quantity": 3, "unit": "grams"},
            {"name": "Turmeric Powder", "quantity": 2, "unit": "grams"},
            {"name": "Vegetable Oil", "quantity": 30, "unit": "ml"},
        ]
    },
    {
        "name": "Idli",
        "description": "Soft steamed rice cakes served with chutney and sambar",
        "category": "Breakfast",
        "cuisine": "South Indian",
        "default_price": 80.00,
        "is_vegetarian": True,
        "spice_level": 1,
        "prep_time_minutes": 20,
        "calories": 180,
        "tags": ["healthy", "vegetarian", "south indian"],
        "ingredients": [
            {"name": "Basmati Rice", "quantity": 80, "unit": "grams"},
            {"name": "Black Lentils", "quantity": 30, "unit": "grams"},
            {"name": "Salt", "quantity": 3, "unit": "grams"},
        ]
    },
    {
        "name": "Vada",
        "description": "Crispy lentil fritters",
        "category": "Snack",
        "cuisine": "South Indian",
        "default_price": 60.00,
        "is_vegetarian": True,
        "spice_level": 2,
        "prep_time_minutes": 20,
        "calories": 220,
        "tags": ["snack", "vegetarian", "south indian"],
        "ingredients": [
            {"name": "Black Lentils", "quantity": 100, "unit": "grams"},
            {"name": "Onion", "quantity": 30, "unit": "grams"},
            {"name": "Green Chili", "quantity": 10, "unit": "grams"},
            {"name": "Ginger", "quantity": 5, "unit": "grams"},
            {"name": "Vegetable Oil", "quantity": 100, "unit": "ml"},
        ]
    },
    {
        "name": "Uttapam",
        "description": "Thick savory pancake with vegetables",
        "category": "Breakfast",
        "cuisine": "South Indian",
        "default_price": 100.00,
        "is_vegetarian": True,
        "spice_level": 1,
        "prep_time_minutes": 20,
        "calories": 240,
        "tags": ["vegetarian", "south indian"],
        "ingredients": [
            {"name": "Basmati Rice", "quantity": 100, "unit": "grams"},
            {"name": "Black Lentils", "quantity": 30, "unit": "grams"},
            {"name": "Onion", "quantity": 30, "unit": "grams"},
            {"name": "Tomato", "quantity": 30, "unit": "grams"},
            {"name": "Bell Pepper", "quantity": 20, "unit": "grams"},
        ]
    },
]

if __name__ == "__main__":
    print(f"✅ Seed data ready!")
    print(f"   - {len(GLOBAL_INGREDIENTS)} Ingredients")
    print(f"   - {len(GLOBAL_DISHES)} Dishes")
    print(f"\nCategories:")
    categories = {}
    for dish in GLOBAL_DISHES:
        cat = dish['category']
        categories[cat] = categories.get(cat, 0) + 1
    for cat, count in categories.items():
        print(f"   - {cat}: {count} dishes")
